ekino_new_relic:
    enabled: false
    application_name: "%env(NEW_RELIC_APP_NAME)%"
    api_key: "%env(NEW_RELIC_API_KEY)%"
    api_host: "%env(NEW_RELIC_API_HOST)%"
    license_key: "%env(NEW_RELIC_LICENSE_KEY)%"
    exceptions: true
    deprecations: false
    logging: true
