framework:
  messenger:
    default_bus: event.bus
    buses:
      event.bus:
        default_middleware: allow_no_handlers

    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'

      domain_events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%default?queue_name=domain_events'
        retry_strategy:
          max_retries: 1

    routing:
      'App\EconumoBundle\Domain\Events\AccountFolderCreatedEvent': domain_events
      'App\EconumoBundle\Domain\Events\BudgetFolderCreatedEvent': domain_events
      'App\EconumoBundle\Domain\Events\RemindPasswordRequestedEvent': domain_events
      'App\EconumoBundle\Domain\Events\UserRegisteredEvent': domain_events
      'App\EconumoBundle\Domain\Events\BudgetEnvelopeCreatedEvent': domain_events
      'App\EconumoBundle\Domain\Events\CategoryCreatedEvent': domain_events
      'App\EconumoBundle\Domain\Events\TagCreatedEvent': domain_events
