---
nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['OPTIONS', 'POST', 'GET']
        allow_headers: ['Content-Type', 'Authorization', 'X-Timezone']
        max_age: 3600
    paths:
        '^/api/doc.json':
            allow_methods: ['OPTIONS', 'GET']
        '^/api/': ~
