security:
    password_hashers:
        App\Domain\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 500

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/user/login-user
            stateless: true
            anonymous: lazy
            json_login:
                check_path: /api/v1/user/login-user
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: App\Infrastructure\Auth\AuthenticationFailureHandler

        api_register:
            pattern: ^/api/v1/user/register-user
            stateless: true
            anonymous: true

        api_remind_password:
            pattern: ^/api/v1/user/remind-password
            stateless: true
            anonymous: true

        api_reset_password:
            pattern: ^/api/v1/user/reset-password
            stateless: true
            anonymous: true

        api_doc:
            pattern: ^/api/doc
            stateless: true
            anonymous: true

        api_system:
            pattern: ^/api/v1/system/
            stateless: true
            anonymous: true

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - {path: ^/api/v1/user/register-user, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/v1/user/login-user, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/v1/user/remind-password, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/v1/user/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/v1/system/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api, roles: IS_AUTHENTICATED_FULLY}

    providers:
        app_user_provider:
            id: App\Infrastructure\Doctrine\UserProvider
