monolog:
    handlers:
        main:
            level: error
            action_level: error
            handler: prod
            include_stacktraces: true
        prod:
            type: error_log
        deprecation_filter:
            handler: black_hole
        black_hole:
            type: "null"