# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/EconumoOneBundle/Infrastructure/Symfony/Form/ValueObjectValidator.php'
      - '../src/EconumoOneBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
      - '../src/EconumoOneBundle/Infrastructure/Doctrine/Migrations/**.php'

  App\EconumoOneBundle\Domain\Service\Currency\CurrencyServiceInterface:
    class: \App\EconumoOneBundle\Domain\Service\Currency\CurrencyService
    arguments:
      $baseCurrency: '%env(string:ECONUMO_CURRENCY_BASE)%'

  App\EconumoOneBundle\Domain\Service\Currency\CurrencyConvertorInterface:
    class: \App\EconumoOneBundle\Domain\Service\Currency\CurrencyConvertor
    arguments:
      $baseCurrency: '%env(string:ECONUMO_CURRENCY_BASE)%'

  App\EconumoOneBundle\Domain\Service\Currency\CurrencyRateServiceInterface:
    class: \App\EconumoOneBundle\Domain\Service\Currency\CurrencyRateService
    arguments:
      $baseCurrency: '%env(string:ECONUMO_CURRENCY_BASE)%'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\EconumoOneBundle\UI\Controller\:
    resource: '../src/EconumoOneBundle/UI/Controller'
    tags: [ 'controller.service_arguments' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\EconumoOneBundle\UI\Middleware\HttpApiResponse\HttpApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  kernel.event_listener.json_request_transformer:
    class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

  App\EconumoOneBundle\Domain\Service\User\UserRegistrationServiceInterface:
    class: App\EconumoOneBundle\Domain\Service\User\UserRegistrationService
    arguments:
      $isRegistrationAllowed: '%env(bool:ECONUMO_ALLOW_REGISTRATION)%'

  App\EconumoOneBundle\Domain\Service\EmailServiceInterface:
    class: App\EconumoOneBundle\Infrastructure\Symfony\Mailer\EmailService
    arguments:
      $fromEmail: '%env(string:ECONUMO_FROM_EMAIL)%'
      $replyToEmail: '%env(string:ECONUMO_REPLY_TO_EMAIL)%'

  App\EconumoOneBundle\Infrastructure\Auth\AuthenticationUpdateTokenPayload:
    arguments:
      $baseCurrency: '%env(string:ECONUMO_CURRENCY_BASE)%'
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onTokenCreated }

  App\EconumoOneBundle\Infrastructure\Auth\AuthenticationSuccessListener:
    class: App\EconumoOneBundle\Infrastructure\Auth\AuthenticationSuccessListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

  App\EconumoOneBundle\UI\Middleware\ProtectSystemApi\ProtectSystemApiListener:
    class: App\EconumoOneBundle\UI\Middleware\ProtectSystemApi\ProtectSystemApiListener
    arguments:
      $token: '%env(ECONUMO_SYSTEM_API_KEY)%'
    tags:
      - { name: kernel.event_listener }

  App\EconumoOneBundle\Infrastructure\Doctrine\SQLiteForeignKeyEnabler:
    tags:
      - { name: doctrine.event_listener, event: postConnect }

  App\EconumoOneBundle\Domain\Service\EncodeServiceInterface:
    class: App\EconumoOneBundle\Domain\Service\EncodeService
    arguments:
      $econumoSalt: '%env(string:ECONUMO_DATA_SALT)%'
