name: "Build Econumo"
on:
  push:
    branches:
      - '*'

jobs:
  build-econumo-one:
    uses: ./.github/workflows/embedded-build-econumo-one.yml
    secrets: inherit

  build-econumo-family:
    needs: build-econumo-one
    uses: ./.github/workflows/embedded-build-econumo-family.yml
    secrets: inherit

  build-econumo-cloud:
    needs: build-econumo-family
    uses: ./.github/workflows/embedded-build-econumo-cloud.yml
    secrets: inherit