name: "Build and test branch"
on:
    push:
        branches:
            - '*'
            - '!main'
            - '!develop'

jobs:
    build_and_test_branch:
        uses: ./.github/workflows/build_and_test.yml
        with:
            DOCKER_IMAGE_APP: "econumo/api-backend:latest"
        secrets: inherit